### ISSUE TITLE
Moteur de recherche

### ISSUE THREAD

**Issue by Krysztophe** [gleu/pgdocs_fr#167]
1) Dans le menu de sélection de la version, la dernière apparaît en avant-dernière. Je m'attendrai à l'ordre chronologique  décroissant : 11 , 10, 9.6...  Et même la v11 présélectionnée pour épargner un clic.

2) Dans les résultst de recherche, même problème. Si je ne sélectionne pas de version, j'ai toutes les versions d'un même thème, mais la 9.6 apparaît aussi en premier, alors que je privilégierais la v11.

**Comment by gleu** [comment]
Désolé pour le retard. Je suis bien d'accord avec toi, et ça mérite un petit travail pour le faire. Je ne sais pas quand, mais je garde l'idée.

**Comment by gleu** [comment]
C'est fait. Merci bien.
