### ISSUE TITLE
Gros numéros sur le PDF

### ISSUE THREAD

**Issue by gleu** [gleu/pgdocs_fr#200]
Présence de gros numéros "1" en bas de la page 10 de la documentation officielle (format pdf):
https://docs.postgresql.fr/12/pg12.pdf

Le problème est également visible sur les pages

- 35 (numérotée 10)
- 135 (numéortée 110)
- 136 (numérotée 111)

**Comment by gleu** [comment]
![doc-postgresql](https://user-images.githubusercontent.com/223410/84543945-aa78c900-acfc-11ea-9c55-36a54dcad0fc.png)

**Comment by dverite** [comment]
Le problème n'apparait pas pour moi en générant le PDF avec les feuilles du styles de la doc en anglais et en utilisant FOP 2.1. C'est ce que je suggèrerais comme solution.

Pour comparaison je mets mon pg13.pdf dans une branche temporaire sur mon repo:
 https://github.com/dverite/pgdocs_fr/blob/pdf/postgresql/pg13.pdf

Les images SVG sont bien intégrées, aussi, alors que sur pg12.pdf ci-dessus il y a un souci de chevauchement avec le texte (voir chapitre 66 sur l'index GIN).

En revanche le style a un peu moins d'habillage, et notamment pas de couleur, comme le PDF de la doc en anglais.

**Comment by dverite** [comment]
Pour mémo le pdf ci-dessus est généré avec docbook-xml 4.5 et les commandes

`xsltproc --path . --stringparam pg.version 13.0 --stringparam img.src.path ./ --stringparam paper.type A4  -o pg.fo stylesheets/stylesheet-fo.xsl postgres.xml`

`fop -fo pg.fo -pdf pg13.pdf`

**Comment by gleu** [comment]
J'ai essayé avec ta méthode et un FOP 2.4 (version par défaut sur Fedora), et en effet, tous les problèmes d'images sont résolus.

J'ai généré la version PDF et la version HTML. Dans les deux cas, ça a bien donné, et c'était beaucoup plus rapide que la génération actuelle. Bref, j'adopte. Je vais travailler là-dessus demain, histoire de refaire ça proprement.

Merci énormément, j'ai beaucoup d'espoir que ça résolve plein de points noirs actuels (les images n'étant que la partie vraiment visible actuellement).

**Comment by gleu** [comment]
Je viens de chronométrer les deux méthodes pour deux formats :

- HTML, ancienne méthode 12 min 31 secondes, nouvelle méthode 38 secondes
- PDF, ancienne méthode 5 minutes 34 secondes, nouvelle méthode 1 minute 7 secondes

Autrement dit, je pourrais facilement générer toutes les versions stables au format HTML et PDF en moins de temps que lorsque je générais juste une version HTML d'une seule version. Totalement dingue, et bienvenu :-)

Bref, je vais bosser là-dessus aujourd'hui.

**Comment by gleu** [comment]
J'avance petit à petit. J'ai maintenant un Makefile pour la génération du PDF, des pages man, des fichiers individuels, du HTML à télécharger. Le HTML du site web pose un peu problème à cause des feuilles de style CSS. Le résultat, pour ce dernier point, est pour l'instant dispo sur https://docs.postgresql.fr/13new/.

Je vais sortir m'aérer les neurones, je reprends demain.

**Comment by dverite** [comment]
Lorsque la doc en anglais a opté pour docbook xml (vers la version 10 je crois) il y a eu pas mal d'optimisations des xsl pour la rapidité, donc on en bénéficie logiquement en reprenant ces éléments.

Pour les CSS web, ça a l'air pas mal actuellement, mais sinon peut-être que s'aligner aussi sur celles de https://www.postgresql.org/docs simplifierait la vie.

Quand on fait view source sur la doc web actuellement, ça commence par 
`<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">` alors que `<!doctype html>`  devrait suffire (voire rien du tout).

**Comment by gleu** [comment]
Oui, je me rappelle des travaux qui avaient été fait pour cela. Je n'avais jamais osé sauter le pas. D'ailleurs, je pense que je ne vais faire que les versions 10 à 13. Les 9.5 et 9.6 resteront sur l'ancien système de génération. De toute façon, elles devraient bientôt disparaître.

Pour les CSS web, la doc est hébergé sur le site de pgfr, donc je respecte au mieux la charte actuelle. La CSS originale de la doc US est conservée, mais il faut que j'ajoute l'en-tête pgfr avec son style. Ça m'a posé quelques soucis aujourd'hui. Il faudrait aussi que j'ajoute une "boite" de recherche, et pourquoi pas un lien rapide avec les autres versions et la doc anglaise. Mais bon, chaque chose en son temps.

Pour le doctype, je regarde ça demain.

Merci.

**Comment by gleu** [comment]
Je viens de commiter les changements pour la génération (voir 22044d4b92ed783d70be68e4936e06134f842d16) et les corrections des problèmes trouvés avec xmllint (voir https://github.com/gleu/pgdocs_fr/commit/d03268e8788feee751126f17cfbb9e6ba0384346), uniquement pour la branche master pour l'instant. Le résultat est dispo sur https://docs.postgresql.fr, et notamment https://docs.postgresql.fr/13/ .

Je vérifie que tout va bien, et j'attaque les branches 12 à 10.

**Comment by gleu** [comment]
Pour en revenir au sujet de ce ticket, le problème n'est plus présent pour les dernières versions de la documentation (11 à 13, certainement 10 prochainement). Voici le résultat pour informations :
![Screenshot from 2020-10-22 09-06-50](https://user-images.githubusercontent.com/223410/96837156-42728600-1446-11eb-9e09-b2de1194eb8d.png)
Je ferme donc ce ticket.
