### ISSUE TITLE
Incohérence de niveau de titre sur Tutorial 1.3

### ISSUE THREAD

**Issue by Krysztophe** [gleu/pgdocs_fr#204]
Cf :
https://docs.postgresql.fr/12/tutorial-createdb.html

Le titre 1.3 apparaît différemment des titres 1.2 et 1.4 (un niveau en dessous ?). La cause ne m'a pas sauté aux yeux. Ça semble le cas depuis des années.

**Comment by gleu** [comment]
Après vérification, c'est le cas d'à peu près tous les chapitres. Je pense que c'est plus un problème de génération (feuilles de style XSLT) que de source. Il faudra que je m'y replonge, ce n'est pas une priorité actuellement (sauf si tu aimes lire du XSLT, et dans ce cas, fais toi plaiz).

**Comment by Krysztophe** [comment]
J'ai beaucoup de vices mais pas celui-là :-)

**Comment by gleu** [comment]
A priori, le problème est corrigé avec les derniers travaux effectués sur la documentation. Je ne sais pas si c'est grâce au changement de génération ou à la correction des balises incorrectes :)
