### ISSUE TITLE
Moteur de recherche : mettre v13 par défaut

### ISSUE THREAD

**Issue by Krysztophe** [gleu/pgdocs_fr#226]
Qui veut une autre version changera.

Cela permettrait de réduire la liste des entrées en éliminant plein de doublons.

**Comment by gleu** [comment]
Maintenant qu'il facile de basculer d'une version à l'autre, je suis plutôt d'accord là-dessus. Je vais voir comment ajouter ça.

**Comment by gleu** [comment]
C'est fait. Mais comme le dit le message de commit, l'option "Toutes les versions" est toujours disponible mais déplacée en fin de liste (pour que le fainéant de dév que je suis se facilite la vie).

**Comment by Krysztophe** [comment]
merci !
