### ISSUE TITLE
Moteur de recherche : le rajouter sur toutes les pages de la doc

### ISSUE THREAD

**Issue by Krysztophe** [gleu/pgdocs_fr#227]
Comme sur le site original, en fait.

Il est fréquent de chercher plusieurs informations à la suite.

**Comment by gleu** [comment]
Beaucoup beaucoup plus compliqué qu'il n'y paraît. Je suis d'accord que ce serait à faire mais ça ne va pas être simple.

**Comment by rjuju** [comment]
En fait @gleu avait déjà résolu le problème dans https://github.com/gleu/pgdocs_fr/commit/a906dd584dc8f2161af7bdc9ffb72462c8ead902.  La PR https://github.com/gleu/pgdocs_fr/pull/228 devrait ajouter la fonctionnalité, avec potentiellement des modifications cosmétiques (ou non) à apporter.

**Comment by gleu** [comment]
Trop de modifications à faire dans ta PR, du coup, j'ai fait une autre solution à ma sauce en m'inspirant quand même de ce que tu avais proposé. C'est dispo sur le site.
