### ISSUE TITLE
superutilisateur -> super-utilisateur

### ISSUE THREAD

**Issue by Krysztophe** [gleu/pgdocs_fr#240]
Je note ici pour ne pas oublier :
Ce n'est pas un adjectif, donc pas "super utilisateur"
On ajoute le tirer à cause de la voyelle.

**Comment by gleu** [comment]
C'est corrigé, pour tous les "super utilisateur" et "superutilisateur". Un peu de standardisation ne peut pas faire de mal :)

Et merci pour l'info.
