### ISSUE TITLE
Erreur non gérée lors de l'intégration des versions

### ISSUE THREAD

**Issue by robinportigliatti** [gleu/pgdocs_fr#243]
Bonjour,

Lorsque je suis la documentation de création du serveur de documentation, à l'étape [d'intégration des version ](https://github.com/gleu/pgdocs_fr/wiki/Cr%C3%A9er-le-serveur-de-documentation) je me retrouve avec l'erreur suivante lors de l'appel au script `./tools/addrelease.php` :
```
PHP Fatal error:  Uncaught Error: Call to undefined function split() in /var/www/html/tools/addrelease.php:101
Stack trace:
#0 {main}
  thrown in /var/www/html/tools/addrelease.php on line 101
```

Cela pourrai venir de la version de php installée car la fonction split a été enlevée à partir de la V7 : https://stackoverflow.com/questions/53454718/how-to-fix-the-error-with-split-in-php/53454731

**Comment by gleu** [comment]
En effet, si tu utilises la version 7 de PHP, la fonction split a été supprimée. Je pense qu'on peut simplement la remplacer par preg_split, qui a l'avantage de fonctionner avec PHP4, 5 et 7.

Je vais réinstaller une VM pour voir.

**Comment by gleu** [comment]
Testé, et ça fonctionne bien a priori. Peux-tu tester de ton côté ? merci.
