### ISSUE TITLE
Version 14 manquante dans la partie recherche

### ISSUE THREAD

**Issue by robinportigliatti** [gleu/pgdocs_fr#249]
Bonjour gleu,

En faisant un petit tour sur https://docs.postgresql.fr/ aujourd'hui je remarque que la version 14 n'apparaît pas dans la liste déroulante des versions de la partie recherche.

**Comment by gleu** [comment]
Salut Robin,

C'est normal. Tant qu'il n'y a pas une version finale (donc en cas de versions beta ou RC), la recherche n'est pas activée pour cette version.

J'ai travaillé sur les dernières traductions hier soir et je viens de placer la version finale sur le serveur. J'en ai profité pour ajouter la recherche sur la version 14.

Merci.
